
/*
===========================================================
SCHEMA - SISTEMA DE INDICADORES (SQL SERVER)
Tabelas no estilo "Protheus": ZSE (setores), ZFU (funcionários/usuários),
ZIN (indicadores), ZIV (valores), ZDR (rascunhos)
===========================================================
*/

IF OBJECT_ID('dbo.ZSE', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ZSE (
        ZSE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ZSE_NOME NVARCHAR(120) NOT NULL,
        ZSE_ATIVO BIT NOT NULL CONSTRAINT DF_ZSE_ATIVO DEFAULT (1)
    );
END;

IF OBJECT_ID('dbo.ZFU', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ZFU (
        ZFU_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ZFU_EMAIL NVARCHAR(160) NOT NULL UNIQUE,
        ZFU_NOME NVARCHAR(160) NOT NULL,
        ZFU_SETOR_ID INT NULL,
        ZFU_ROLE NVARCHAR(20) NOT NULL CONSTRAINT DF_ZFU_ROLE DEFAULT ('PADRAO'), -- PADRAO | LIDER | GESTAO
        ZFU_SENHA_HASH NVARCHAR(255) NULL,
        ZFU_ATIVO BIT NOT NULL CONSTRAINT DF_ZFU_ATIVO DEFAULT (1),
        CONSTRAINT FK_ZFU_ZSE FOREIGN KEY (ZFU_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID)
    );
END;

IF OBJECT_ID('dbo.ZIN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ZIN (
        ZIN_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ZIN_SETOR_ID INT NOT NULL,
        ZIN_NOME NVARCHAR(400) NOT NULL,
        ZIN_TIPO NVARCHAR(20) NOT NULL CONSTRAINT DF_ZIN_TIPO DEFAULT ('numero'), -- numero | texto | data
        ZIN_UNIDADE NVARCHAR(20) NULL,
        ZIN_META DECIMAL(18,4) NULL,
        ZIN_ATIVO BIT NOT NULL CONSTRAINT DF_ZIN_ATIVO DEFAULT (1),
        CONSTRAINT FK_ZIN_ZSE FOREIGN KEY (ZIN_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID)
    );
END;

IF OBJECT_ID('dbo.ZIV', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ZIV (
        ZIV_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ZIV_INDICADOR_ID INT NOT NULL,
        ZIV_SETOR_ID INT NOT NULL,
        ZIV_FUNCIONARIO_ID INT NOT NULL,
        ZIV_PERIODO DATE NOT NULL, -- sempre o dia 01 do mês
        ZIV_VALOR NVARCHAR(255) NULL,
        ZIV_CRIADO_EM DATETIME2 NOT NULL CONSTRAINT DF_ZIV_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        ZIV_ATUALIZADO_EM DATETIME2 NOT NULL CONSTRAINT DF_ZIV_ATUALIZADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT FK_ZIV_ZIN FOREIGN KEY (ZIV_INDICADOR_ID) REFERENCES dbo.ZIN(ZIN_ID),
        CONSTRAINT FK_ZIV_ZSE FOREIGN KEY (ZIV_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID),
        CONSTRAINT FK_ZIV_ZFU FOREIGN KEY (ZIV_FUNCIONARIO_ID) REFERENCES dbo.ZFU(ZFU_ID),
        CONSTRAINT UQ_ZIV_IND_SET_PER UNIQUE (ZIV_INDICADOR_ID, ZIV_SETOR_ID, ZIV_PERIODO)
    );
END;

IF OBJECT_ID('dbo.ZDR', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ZDR (
        ZDR_ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ZDR_INDICADOR_ID INT NOT NULL,
        ZDR_SETOR_ID INT NOT NULL,
        ZDR_FUNCIONARIO_ID INT NOT NULL,
        ZDR_PERIODO DATE NOT NULL,
        ZDR_VALOR NVARCHAR(255) NULL,
        ZDR_CRIADO_EM DATETIME2 NOT NULL CONSTRAINT DF_ZDR_CRIADO_EM DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT FK_ZDR_ZIN FOREIGN KEY (ZDR_INDICADOR_ID) REFERENCES dbo.ZIN(ZIN_ID),
        CONSTRAINT FK_ZDR_ZSE FOREIGN KEY (ZDR_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID),
        CONSTRAINT FK_ZDR_ZFU FOREIGN KEY (ZDR_FUNCIONARIO_ID) REFERENCES dbo.ZFU(ZFU_ID)
    );
END;
