/* ============================================================
   CRIAÇÃO DO BANCO
   ============================================================ */
CREATE DATABASE PRD_WEB_APP;
GO

USE PRD_WEB_APP;
GO

/* ============================================================
   ZSE - SETORES
   ============================================================ */
CREATE TABLE dbo.ZSE (
    ZSE_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZSE PRIMARY KEY,
    ZSE_NOME NVARCHAR(200) NOT NULL,
    ZSE_ATIVO BIT NOT NULL CONSTRAINT DF_ZSE_ATIVO DEFAULT (1),
    ZSE_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZSE_CRIADO DEFAULT (SYSUTCDATETIME()),
    ZSE_ATUALIZADO_EM DATETIME2(0) NULL
);
GO

CREATE UNIQUE INDEX UX_ZSE_NOME ON dbo.ZSE (ZSE_NOME);
GO

/* ============================================================
   ZFU - FUNCIONÁRIOS
   (SEM PERFIL – compatível com o Python)
   ============================================================ */
CREATE TABLE dbo.ZFU (
    ZFU_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZFU PRIMARY KEY,
    ZFU_NOME NVARCHAR(200) NOT NULL,
    ZFU_EMAIL NVARCHAR(320) NOT NULL,
    ZFU_SETOR_ID INT NULL,
    ZFU_NIVEL TINYINT NOT NULL CONSTRAINT DF_ZFU_NIVEL DEFAULT (1), -- 1..5
    ZFU_SENHA_HASH NVARCHAR(255) NOT NULL,
    ZFU_ATIVO BIT NOT NULL CONSTRAINT DF_ZFU_ATIVO DEFAULT (1),
    ZFU_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZFU_CRIADO DEFAULT (SYSUTCDATETIME()),
    ZFU_ATUALIZADO_EM DATETIME2(0) NULL,
    CONSTRAINT FK_ZFU_ZSE FOREIGN KEY (ZFU_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID)
);
GO

CREATE UNIQUE INDEX UX_ZFU_EMAIL ON dbo.ZFU (ZFU_EMAIL);
GO

/* ============================================================
   ZIN - INDICADORES
   ============================================================ */
CREATE TABLE dbo.ZIN (
    ZIN_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZIN PRIMARY KEY,
    ZIN_SETOR_ID INT NOT NULL,
    ZIN_CODIGO NVARCHAR(50) NOT NULL,
    ZIN_NOME NVARCHAR(400) NOT NULL,
    ZIN_TIPO NVARCHAR(50) NULL,
    ZIN_UNIDADE NVARCHAR(50) NULL,
    ZIN_META NVARCHAR(100) NULL,
    ZIN_RESPONSAVEL_ID INT NULL,
    ZIN_ATIVO BIT NOT NULL CONSTRAINT DF_ZIN_ATIVO DEFAULT (1),
    ZIN_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZIN_CRIADO DEFAULT (SYSUTCDATETIME()),
    ZIN_ATUALIZADO_EM DATETIME2(0) NULL,
    CONSTRAINT FK_ZIN_ZSE FOREIGN KEY (ZIN_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID),
    CONSTRAINT FK_ZIN_RESP FOREIGN KEY (ZIN_RESPONSAVEL_ID) REFERENCES dbo.ZFU(ZFU_ID)
);
GO

CREATE UNIQUE INDEX UX_ZIN_SETOR_CODIGO
ON dbo.ZIN (ZIN_SETOR_ID, ZIN_CODIGO);
GO

/* ============================================================
   ZIV - VALORES DEFINITIVOS
   ============================================================ */
CREATE TABLE dbo.ZIV (
    ZIV_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZIV PRIMARY KEY,
    ZIV_INDICADOR_ID INT NOT NULL,
    ZIV_SETOR_ID INT NOT NULL,
    ZIV_FUNCIONARIO_ID INT NULL,
    ZIV_PERIODO DATE NOT NULL,
    ZIV_VALOR NVARCHAR(200) NULL,
    ZIV_CRIADO_EM DATETIME2(0) NOT NULL,
    ZIV_ATUALIZADO_EM DATETIME2(0) NOT NULL,
    CONSTRAINT FK_ZIV_ZIN FOREIGN KEY (ZIV_INDICADOR_ID) REFERENCES dbo.ZIN(ZIN_ID),
    CONSTRAINT FK_ZIV_ZSE FOREIGN KEY (ZIV_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID),
    CONSTRAINT FK_ZIV_ZFU FOREIGN KEY (ZIV_FUNCIONARIO_ID) REFERENCES dbo.ZFU(ZFU_ID)
);
GO

CREATE UNIQUE INDEX UX_ZIV_IND_SET_PER
ON dbo.ZIV (ZIV_INDICADOR_ID, ZIV_SETOR_ID, ZIV_PERIODO);
GO

CREATE INDEX IX_ZIV_SETOR_PERIODO
ON dbo.ZIV (ZIV_SETOR_ID, ZIV_PERIODO)
INCLUDE (ZIV_INDICADOR_ID, ZIV_VALOR);
GO

/* ============================================================
   ZDR - DRAFTS (RASCUNHOS POR INDICADOR) - MODELO USADO PELO app.py
   ============================================================ */
CREATE TABLE dbo.ZDR (
    ZDR_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZDR PRIMARY KEY,
    ZDR_INDICADOR_ID INT NOT NULL,
    ZDR_SETOR_ID INT NOT NULL,
    ZDR_FUNCIONARIO_ID INT NULL,
    ZDR_PERIODO DATE NOT NULL,
    ZDR_VALOR NVARCHAR(200) NULL,
    ZDR_STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_ZDR_STATUS DEFAULT ('DRAFT'), -- DRAFT|PENDING|APPROVED|REJECTED
    ZDR_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZDR_CRIADO DEFAULT (SYSUTCDATETIME()),
    ZDR_ENVIADO_EM DATETIME2(0) NULL,
    ZDR_APROVADO_EM DATETIME2(0) NULL,
    ZDR_APROVADO_POR INT NULL,
    ZDR_REJEITADO_EM DATETIME2(0) NULL,
    ZDR_REJEITADO_POR INT NULL,
    ZDR_REJEITADO_MOTIVO NVARCHAR(500) NULL,
    CONSTRAINT FK_ZDR_ZIN FOREIGN KEY (ZDR_INDICADOR_ID) REFERENCES dbo.ZIN(ZIN_ID),
    CONSTRAINT FK_ZDR_ZSE FOREIGN KEY (ZDR_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID),
    CONSTRAINT FK_ZDR_ZFU FOREIGN KEY (ZDR_FUNCIONARIO_ID) REFERENCES dbo.ZFU(ZFU_ID),
    CONSTRAINT FK_ZDR_APROVADOR FOREIGN KEY (ZDR_APROVADO_POR) REFERENCES dbo.ZFU(ZFU_ID),
    CONSTRAINT FK_ZDR_REJEITADOR FOREIGN KEY (ZDR_REJEITADO_POR) REFERENCES dbo.ZFU(ZFU_ID)
);
GO

CREATE INDEX IX_ZDR_SETOR_PERIODO_STATUS ON dbo.ZDR (ZDR_SETOR_ID, ZDR_PERIODO, ZDR_STATUS);
GO

CREATE INDEX IX_ZDR_SETOR_PERIODO
ON dbo.ZDR (ZDR_SETOR_ID, ZDR_PERIODO)
INCLUDE (ZDR_INDICADOR_ID, ZDR_VALOR, ZDR_CRIADO_EM);
GO


-- Usuário ADM inicial é criado automaticamente pelo app.py se não existir (SEED_ADMIN_EMAIL/SEED_ADMIN_PASSWORD no .env)

/* ============================================================
   ALTERACOES (banco existente)
   ============================================================ */
-- ZDR (rascunhos simples usados pelo app.py)
IF COL_LENGTH('dbo.ZDR', 'ZDR_INDICADOR_ID') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_INDICADOR_ID INT NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_SETOR_ID') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_SETOR_ID INT NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_FUNCIONARIO_ID') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_FUNCIONARIO_ID INT NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_PERIODO') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_PERIODO DATE NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_VALOR') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_VALOR NVARCHAR(200) NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_STATUS') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_ZDR_STATUS_APP DEFAULT ('DRAFT');
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_CRIADO_EM') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZDR_CRIADO_APP DEFAULT (SYSUTCDATETIME());
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_ENVIADO_EM') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_ENVIADO_EM DATETIME2(0) NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_APROVADO_EM') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_APROVADO_EM DATETIME2(0) NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_APROVADO_POR') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_APROVADO_POR INT NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_REJEITADO_EM') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_REJEITADO_EM DATETIME2(0) NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_REJEITADO_POR') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_REJEITADO_POR INT NULL;
END;
GO

IF COL_LENGTH('dbo.ZDR', 'ZDR_REJEITADO_MOTIVO') IS NULL
BEGIN
    ALTER TABLE dbo.ZDR ADD ZDR_REJEITADO_MOTIVO NVARCHAR(500) NULL;
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ZDR_ZIN'
)
BEGIN
    ALTER TABLE dbo.ZDR
    ADD CONSTRAINT FK_ZDR_ZIN FOREIGN KEY (ZDR_INDICADOR_ID)
    REFERENCES dbo.ZIN (ZIN_ID);
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ZDR_ZSE'
)
BEGIN
    ALTER TABLE dbo.ZDR
    ADD CONSTRAINT FK_ZDR_ZSE FOREIGN KEY (ZDR_SETOR_ID)
    REFERENCES dbo.ZSE (ZSE_ID);
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ZDR_ZFU'
)
BEGIN
    ALTER TABLE dbo.ZDR
    ADD CONSTRAINT FK_ZDR_ZFU FOREIGN KEY (ZDR_FUNCIONARIO_ID)
    REFERENCES dbo.ZFU (ZFU_ID);
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ZDR_APROVADOR'
)
BEGIN
    ALTER TABLE dbo.ZDR
    ADD CONSTRAINT FK_ZDR_APROVADOR FOREIGN KEY (ZDR_APROVADO_POR)
    REFERENCES dbo.ZFU (ZFU_ID);
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ZDR_REJEITADOR'
)
BEGIN
    ALTER TABLE dbo.ZDR
    ADD CONSTRAINT FK_ZDR_REJEITADOR FOREIGN KEY (ZDR_REJEITADO_POR)
    REFERENCES dbo.ZFU (ZFU_ID);
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes WHERE name = 'IX_ZDR_SETOR_PERIODO_STATUS'
)
BEGIN
    CREATE INDEX IX_ZDR_SETOR_PERIODO_STATUS
    ON dbo.ZDR (ZDR_SETOR_ID, ZDR_PERIODO, ZDR_STATUS);
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.indexes WHERE name = 'IX_ZDR_SETOR_PERIODO'
)
BEGIN
    CREATE INDEX IX_ZDR_SETOR_PERIODO
    ON dbo.ZDR (ZDR_SETOR_ID, ZDR_PERIODO)
    INCLUDE (ZDR_INDICADOR_ID, ZDR_VALOR, ZDR_CRIADO_EM);
END;
GO
IF COL_LENGTH('dbo.ZIN', 'ZIN_RESPONSAVEL_ID') IS NULL
BEGIN
    ALTER TABLE dbo.ZIN ADD ZIN_RESPONSAVEL_ID INT NULL;
END;
GO

IF COL_LENGTH('dbo.ZIN', 'ZIN_OBRIGATORIO') IS NULL
BEGIN
    ALTER TABLE dbo.ZIN ADD ZIN_OBRIGATORIO BIT NOT NULL CONSTRAINT DF_ZIN_OBRIGATORIO DEFAULT (0);
END;
GO

IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_ZIN_RESP'
)
BEGIN
    ALTER TABLE dbo.ZIN
    ADD CONSTRAINT FK_ZIN_RESP FOREIGN KEY (ZIN_RESPONSAVEL_ID)
    REFERENCES dbo.ZFU (ZFU_ID);
END;
GO

/* ============================================================
   VIEW POWER BI - SOMENTE DADOS OFICIAIS (ZIV)
   ============================================================ */
CREATE OR ALTER VIEW dbo.VW_PBI_INDICADORES_OFICIAIS
AS
SELECT
    ziv.ZIV_ID,
    ziv.ZIV_PERIODO,
    ziv.ZIV_VALOR,
    ziv.ZIV_CRIADO_EM,
    ziv.ZIV_ATUALIZADO_EM,
    zse.ZSE_ID,
    zse.ZSE_NOME,
    zin.ZIN_ID,
    zin.ZIN_CODIGO,
    zin.ZIN_NOME,
    zin.ZIN_TIPO,
    zin.ZIN_UNIDADE,
    zin.ZIN_META,
    zfu.ZFU_ID AS FUNCIONARIO_ID,
    zfu.ZFU_NOME AS FUNCIONARIO_NOME,
    zfu.ZFU_EMAIL AS FUNCIONARIO_EMAIL
FROM dbo.ZIV ziv
INNER JOIN dbo.ZSE zse ON zse.ZSE_ID = ziv.ZIV_SETOR_ID
INNER JOIN dbo.ZIN zin ON zin.ZIN_ID = ziv.ZIV_INDICADOR_ID
LEFT JOIN dbo.ZFU zfu ON zfu.ZFU_ID = ziv.ZIV_FUNCIONARIO_ID;
GO

/* ============================================================
   MIGRACAO - REMOVER ZIN_TIPO (TODOS INDICADORES = TEXTO)
   ============================================================ */
IF COL_LENGTH('dbo.ZIN', 'ZIN_TIPO') IS NOT NULL
BEGIN
    UPDATE dbo.ZIN
    SET ZIN_TIPO = 'text'
    WHERE ZIN_TIPO IS NULL OR LTRIM(RTRIM(ZIN_TIPO)) = '';

    ALTER TABLE dbo.ZIN DROP COLUMN ZIN_TIPO;
END;
GO
