/* ============================================================
   CRIAÇÃO DO BANCO
   ============================================================ */
CREATE DATABASE PRD_WEB_APP;
GO

USE PRD_WEB_APP;
GO

/* ============================================================
   ZSE - SETORES
   ============================================================ */
CREATE TABLE dbo.ZSE (
    ZSE_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZSE PRIMARY KEY,
    ZSE_NOME NVARCHAR(200) NOT NULL,
    ZSE_ATIVO BIT NOT NULL CONSTRAINT DF_ZSE_ATIVO DEFAULT (1),
    ZSE_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZSE_CRIADO DEFAULT (SYSUTCDATETIME()),
    ZSE_ATUALIZADO_EM DATETIME2(0) NULL
);
GO

CREATE UNIQUE INDEX UX_ZSE_NOME ON dbo.ZSE (ZSE_NOME);
GO

/* ============================================================
   ZFU - FUNCIONÁRIOS
   (SEM PERFIL – compatível com o Python)
   ============================================================ */
CREATE TABLE dbo.ZFU (
    ZFU_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZFU PRIMARY KEY,
    ZFU_NOME NVARCHAR(200) NOT NULL,
    ZFU_EMAIL NVARCHAR(320) NOT NULL,
    ZFU_SETOR_ID INT NULL,
    ZFU_NIVEL TINYINT NOT NULL CONSTRAINT DF_ZFU_NIVEL DEFAULT (1), -- 1..5
    ZFU_SENHA_HASH NVARCHAR(255) NOT NULL,
    ZFU_ATIVO BIT NOT NULL CONSTRAINT DF_ZFU_ATIVO DEFAULT (1),
    ZFU_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZFU_CRIADO DEFAULT (SYSUTCDATETIME()),
    ZFU_ATUALIZADO_EM DATETIME2(0) NULL,
    CONSTRAINT FK_ZFU_ZSE FOREIGN KEY (ZFU_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID)
);
GO

CREATE UNIQUE INDEX UX_ZFU_EMAIL ON dbo.ZFU (ZFU_EMAIL);
GO

/* ============================================================
   ZIN - INDICADORES
   ============================================================ */
CREATE TABLE dbo.ZIN (
    ZIN_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZIN PRIMARY KEY,
    ZIN_SETOR_ID INT NOT NULL,
    ZIN_CODIGO NVARCHAR(50) NOT NULL,
    ZIN_NOME NVARCHAR(400) NOT NULL,
    ZIN_TIPO NVARCHAR(50) NULL,
    ZIN_UNIDADE NVARCHAR(50) NULL,
    ZIN_META NVARCHAR(100) NULL,
    ZIN_ATIVO BIT NOT NULL CONSTRAINT DF_ZIN_ATIVO DEFAULT (1),
    ZIN_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZIN_CRIADO DEFAULT (SYSUTCDATETIME()),
    ZIN_ATUALIZADO_EM DATETIME2(0) NULL,
    CONSTRAINT FK_ZIN_ZSE FOREIGN KEY (ZIN_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID)
);
GO

CREATE UNIQUE INDEX UX_ZIN_SETOR_CODIGO
ON dbo.ZIN (ZIN_SETOR_ID, ZIN_CODIGO);
GO

/* ============================================================
   ZIV - VALORES DEFINITIVOS
   ============================================================ */
CREATE TABLE dbo.ZIV (
    ZIV_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZIV PRIMARY KEY,
    ZIV_INDICADOR_ID INT NOT NULL,
    ZIV_SETOR_ID INT NOT NULL,
    ZIV_FUNCIONARIO_ID INT NULL,
    ZIV_PERIODO DATE NOT NULL,
    ZIV_VALOR NVARCHAR(200) NULL,
    ZIV_CRIADO_EM DATETIME2(0) NOT NULL,
    ZIV_ATUALIZADO_EM DATETIME2(0) NOT NULL,
    CONSTRAINT FK_ZIV_ZIN FOREIGN KEY (ZIV_INDICADOR_ID) REFERENCES dbo.ZIN(ZIN_ID),
    CONSTRAINT FK_ZIV_ZSE FOREIGN KEY (ZIV_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID),
    CONSTRAINT FK_ZIV_ZFU FOREIGN KEY (ZIV_FUNCIONARIO_ID) REFERENCES dbo.ZFU(ZFU_ID)
);
GO

CREATE UNIQUE INDEX UX_ZIV_IND_SET_PER
ON dbo.ZIV (ZIV_INDICADOR_ID, ZIV_SETOR_ID, ZIV_PERIODO);
GO

CREATE INDEX IX_ZIV_SETOR_PERIODO
ON dbo.ZIV (ZIV_SETOR_ID, ZIV_PERIODO)
INCLUDE (ZIV_INDICADOR_ID, ZIV_VALOR);
GO

/* ============================================================
   ZDR - DRAFTS (RASCUNHOS)
   ============================================================ */
CREATE TABLE dbo.ZDR (
    ZDR_ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ZDR PRIMARY KEY,
    ZDR_INDICADOR_ID INT NOT NULL,
    ZDR_SETOR_ID INT NOT NULL,
    ZDR_FUNCIONARIO_ID INT NULL,
    ZDR_PERIODO DATE NOT NULL,
    ZDR_VALOR NVARCHAR(200) NULL,

    ZDR_STATUS NVARCHAR(20) NOT NULL CONSTRAINT DF_ZDR_STATUS DEFAULT ('DRAFT'), -- DRAFT|PENDING|APPROVED|REJECTED
    ZDR_CRIADO_EM DATETIME2(0) NOT NULL CONSTRAINT DF_ZDR_CRIADO DEFAULT (SYSUTCDATETIME()),
    ZDR_ENVIADO_EM DATETIME2(0) NULL,
    ZDR_APROVADO_EM DATETIME2(0) NULL,
    ZDR_APROVADO_POR INT NULL,

    CONSTRAINT FK_ZDR_ZIN FOREIGN KEY (ZDR_INDICADOR_ID) REFERENCES dbo.ZIN(ZIN_ID),
    CONSTRAINT FK_ZDR_ZSE FOREIGN KEY (ZDR_SETOR_ID) REFERENCES dbo.ZSE(ZSE_ID),
    CONSTRAINT FK_ZDR_ZFU FOREIGN KEY (ZDR_FUNCIONARIO_ID) REFERENCES dbo.ZFU(ZFU_ID),
    CONSTRAINT FK_ZDR_APROVADOR FOREIGN KEY (ZDR_APROVADO_POR) REFERENCES dbo.ZFU(ZFU_ID)
);
GO

CREATE INDEX IX_ZDR_SETOR_PERIODO_STATUS ON dbo.ZDR (ZDR_SETOR_ID, ZDR_PERIODO, ZDR_STATUS);
GO

CREATE INDEX IX_ZDR_SETOR_PERIODO
ON dbo.ZDR (ZDR_SETOR_ID, ZDR_PERIODO)
INCLUDE (ZDR_INDICADOR_ID, ZDR_VALOR, ZDR_CRIADO_EM);
GO


-- Usuário ADM inicial é criado automaticamente pelo app.py se não existir (SEED_ADMIN_EMAIL/SEED_ADMIN_PASSWORD no .env)
